networks:
  base-net:
    driver: bridge

services:
  # Server
  db:
    container_name: oracle-db
    image: gvenzl/oracle-xe:latest
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${SPRING_DATASOURCE_USERNAME}
      APP_USER_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '1521:1521'
    networks:
      - base-net
    volumes:
      - ./data/oracle:/opt/oracle/oradata
    healthcheck:
      test: ['CMD', 'lsnrctl', 'status']
      interval: 15s
      timeout: 5s
      retries: 15
    deploy:
      resources:
        limits:
          memory: 2G
  server:
    container_name: backend
    image: backend:latest
    environment:
      ###   Spring DB Config
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER: ${SPRING_DATASOURCE_DRIVER}
      ###   Default account
      # Admin
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ###   Mailtrap Config
      # MAIL_HOST: ${MAIL_HOST}
      # MAIL_PORT: ${MAIL_PORT}
      # MAIL_USERNAME: ${MAIL_USERNAME}
      # MAIL_PASSWORD: ${MAIL_PASSWORD}
      ###   Refresh Token Config
      JWT_COOKIE_NAME: ${JWT_COOKIE_NAME}
      JWT_COOKIE_REFRESH_NAME: ${JWT_COOKIE_REFRESH_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
    build:
      context: ../backend
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '${SPRING_PORT}:8888'
    networks:
      - base-net
    depends_on:
      db:
        condition: service_healthy
    restart: always
