server.port=8888
# Database
db.url=${DB_URL}
db.user=${DB_USER}
db.pass=${DB_PASS}
db.driver=${DB_DRIVER}
# JWT config
app.jwtCookieName=${JWT_COOKIE_NAME}
app.jwtRefreshCookieName=${JWT_COOKIE_REFRESH_NAME}
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationsMs=${JWT_EXPIRATION}
app.jwtRefreshExpirationsMs=${JWT_REFRESH_EXPIRATION}
# Setup config
setup.admin.username=${ADMIN_USERNAME}
setup.admin.password=${ADMIN_PASSWORD}
setup.stock.username=${STOCK_USERNAME}
setup.stock.password=${STOCK_PASSWORD}
setup.sale.username=${SALE_USERNAME}
setup.sale.password=${SALE_PASSWORD}
# Flyway
flyway.locations=classpath:db/migration
# Config Cloudinary
cloudinary.folderName=${CLOUDINARY_FOLDER_NAME}
cloudinary.cloudName=${CLOUDINARY_CLOUD_NAME}
cloudinary.apiKey=${CLOUDINARY_API_KEY}
cloudinary.apiSecret=${CLOUDINARY_API_SECRET}
# Open Router
openRouter.url=${OPEN_ROUTER_URL}
openRouter.api=${OPEN_ROUTER_API}
openRouter.model=${OPEN_ROUTER_MODEL}
# Mail
mail.enabled=${MAIL_ENABLED}
mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
mail.from=${MAIL_FROM}
# Frontend URL (cho reset password link)
app.frontendUrl=${FRONTEND_URL}