server:
  port: 8888
# Swagger config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  application:
    name: backend
  # Database config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  # JPA config
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: false
        dialect: org.hibernate.dialect.OracleDialect
  sql:
    init:
      mode: never
      schema-locations: classpath:db/migration
      data-locations: classpath:db/migration
  # Config Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
    #Config JWT
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
app:
  jwtCookieName: ${JWT_COOKIE_NAME}
  jwtRefreshCookieName: ${JWT_COOKIE_REFRESH_NAME}
  jwtSecret: ${JWT_SECRET}
  jwtExpirationsMs: ${JWT_EXPIRATION}
  jwtRefreshExpirationsMs: ${JWT_REFRESH_EXPIRATION}
  setup:
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  #Config Cloudinary
  cloudinary:
    folderName: ${CLOUDINARY_FOLDER_NAME}
    cloudName: ${CLOUDINARY_CLOUD_NAME}
    apiKey: ${CLOUDINARY_API_KEY}
    apiSecret: ${CLOUDINARY_API_SECRET}
