# Port
server:
  port: 8888
# Swagger Config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
# Spring Config
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # Database
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      schema-locations: classpath:db/migration
      data-locations: classpath:db/migration
  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
  # Mail
  mail:
    enabled: ${MAIL_ENABLED}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}

# JWT config
app:
  jwtCookieName: ${JWT_COOKIE_NAME}
  jwtRefreshCookieName: ${JWT_COOKIE_REFRESH_NAME}
  jwtSecret: ${JWT_SECRET}
  jwtExpirationsMs: ${JWT_EXPIRATION}
  jwtRefreshExpirationsMs: ${JWT_REFRESH_EXPIRATION}
  # Frontend URL (cho reset password link)
  frontendUrl: ${FRONTEND_URL}
# Config Cloudinary
cloudinary:
  folderName: ${CLOUDINARY_FOLDER_NAME}
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
# Open Router
langchain4j:
  open-ai:
    chat-model:
      base-url: ${OPEN_ROUTER_URL}
      api-key: ${OPEN_ROUTER_API}
      model-name: ${OPEN_ROUTER_MODEL}
      log-requests: true
      log-responses: true
      timeout: 60s
      max-retries: 0
      temperature: 0.0
