CREATE TABLE roles
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(50)                                          NOT NULL,
    description VARCHAR2(255),
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users
(
    id                NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR2(100)                                         NOT NULL,
    full_name         VARCHAR2(255),
    password          VARCHAR2(255)                                         NOT NULL,
    gender            NUMBER(1),
    date_of_birth     DATE,
    phone_number      VARCHAR2(20),
    email             VARCHAR2(255),
    status            VARCHAR2(20)                DEFAULT 'ACTIVE',
    is_password_reset NUMBER(1)                   DEFAULT 0                 NOT NULL,
    role_id           NUMBER(19, 0)                                         NOT NULL,
    is_deleted        NUMBER(1)                   DEFAULT 0                 NOT NULL,
    last_login        TIMESTAMP(6) WITH TIME ZONE,
    created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone UNIQUE (phone_number),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT ck_users_is_deleted CHECK ( is_deleted IN (0, 1)),
    CONSTRAINT ck_users_gender CHECK (gender IN (0, 1, 2))
);

CREATE TABLE suppliers
(
    id             NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR2(255)                                         NOT NULL,
    contact_person VARCHAR2(100),
    phone_number   VARCHAR2(20),
    email          VARCHAR2(255),
    address        VARCHAR2(500),
    tax_code       VARCHAR2(50),
    status         VARCHAR2(20)                DEFAULT 'ACTIVE',
    is_deleted     NUMBER(1)                   DEFAULT 0                 NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_suppliers PRIMARY KEY (id),
    CONSTRAINT uk_suppliers_name UNIQUE (name),
    CONSTRAINT ck_suppliers_is_deleted CHECK ( is_deleted IN (0, 1)),
    CONSTRAINT ck_suppliers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);


CREATE TABLE categories
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(100)                                         NOT NULL,
    description VARCHAR2(255),
    is_deleted  NUMBER(1)                   DEFAULT 0                 NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT ck_categories_is_deleted CHECK ( is_deleted IN (0, 1))
);

CREATE TABLE customers
(
    id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    phone_number VARCHAR2(20)                                          NOT NULL,
    full_name    VARCHAR2(255)                                         NOT NULL,
    email        VARCHAR2(255),
    address      VARCHAR2(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uk_customers_phone UNIQUE (phone_number),
    CONSTRAINT uk_customers_email UNIQUE (email)
);

CREATE TABLE products
(
    id               NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    category_id      NUMBER(19, 0)                                         NOT NULL,
    sku              VARCHAR2(50)                                          NOT NULL,
    name             VARCHAR2(255),
    image_url        VARCHAR2(500),
    specifications   CLOB,
    warranty_period  NUMBER(3)                   DEFAULT 12,
    has_imei         NUMBER(1)                   DEFAULT 1,
    price_import_std NUMBER(19, 2)               DEFAULT 0,
    price_export_std NUMBER(19, 2)               DEFAULT 0,
    current_stock    NUMBER(10)                  DEFAULT 0                 NOT NULL,
    min_threshold    NUMBER(10)                  DEFAULT 5,
    status           VARCHAR2(20)                DEFAULT 'ACTIVE',
    is_deleted       NUMBER(1)                   DEFAULT 0                 NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_products_is_deleted CHECK ( is_deleted IN (0, 1)),
    CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE warehouses
(
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR2(100)                                         NOT NULL,
    address    VARCHAR2(500),
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_warehouses PRIMARY KEY (id)
);

CREATE TABLE warehouse_locations
(
    id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    warehouse_id NUMBER(19, 0)         NOT NULL,
    zone_name    VARCHAR2(50),
    row_num      VARCHAR2(20),
    shelf_num    VARCHAR2(20),
    bin_num      VARCHAR2(20),
    capacity     NUMBER(10) DEFAULT 20 NOT NULL,
    CONSTRAINT pk_warehouse_locations PRIMARY KEY (id),
    CONSTRAINT fk_loc_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT uk_location_coords UNIQUE (warehouse_id, zone_name, row_num, shelf_num, bin_num)
);


CREATE TABLE orders
(
    id             NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    sale_id        NUMBER(19, 0)                                         NOT NULL,
    customer_id    NUMBER(19, 0)                                         NOT NULL,
    total_amount   NUMBER(19, 2)               DEFAULT 0,
    payment_method VARCHAR2(50),
    status         VARCHAR2(20)                DEFAULT 'PENDING',
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_user_id FOREIGN KEY (sale_id) REFERENCES users (id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELED', 'RETURNED'))
);

CREATE TABLE product_items
(
    id                   NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    product_id           NUMBER(19, 0) NOT NULL,
    location_id          NUMBER(19, 0),
    imei                 VARCHAR2(50)  NOT NULL,
    cost_price           NUMBER(19, 2)               DEFAULT 0,
    supplier_id          NUMBER(19, 0),
    condition            VARCHAR2(50)                DEFAULT 'NEW',
    status               VARCHAR2(20)                DEFAULT 'AVAILABLE',
    order_id             NUMBER(19, 0),
    warranty_expiry_date TIMESTAMP(6) WITH TIME ZONE,
    import_date          TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sold_date            TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT pk_product_items PRIMARY KEY (id),
    CONSTRAINT uk_product_items_imei UNIQUE (imei),
    CONSTRAINT fk_items_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_items_prod_id FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_items_location FOREIGN KEY (location_id) REFERENCES warehouse_locations (id),
    CONSTRAINT ck_items_status CHECK (status IN ('AVAILABLE', 'SOLD', 'DAMAGED', 'RETURNED'))
);

CREATE TABLE order_items
(
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    order_id   NUMBER(19, 0) NOT NULL,
    product_id NUMBER(19, 0) NOT NULL,
    quantity   NUMBER(10)    NOT NULL,
    unit_price NUMBER(19, 2) NOT NULL,

    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_items_prod FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE refresh_tokens
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER(19, 0)               NOT NULL,
    token       VARCHAR2(500)               NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT fk_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE audit_logs
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER(19, 0),
    action      VARCHAR2(100),
    entity_name VARCHAR2(100),
    entity_id   VARCHAR2(100),
    status      VARCHAR2(50),
    details     CLOB,
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE stock_movements
(
    id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    product_id   NUMBER(19, 0)                                         NOT NULL,
    type         VARCHAR2(20)                                          NOT NULL,
    action_type  VARCHAR2(50)                                          NOT NULL,
    quantity     NUMBER(10)                                            NOT NULL,
    supplier_id  NUMBER(19, 0),
    reference_id NUMBER(19, 0),
    created_by   NUMBER(19, 0)                                         NOT NULL,
    note         VARCHAR2(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_stock_movements PRIMARY KEY (id),
    CONSTRAINT fk_move_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
    CONSTRAINT fk_move_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_move_type CHECK (type IN ('IMPORT', 'EXPORT', 'ADJUST'))
);

CREATE TABLE warranty_claims
(
    id                NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    product_item_id   NUMBER(19, 0),
    customer_id       NUMBER(19, 0) NOT NULL,
    created_by        NUMBER(19, 0) NOT NULL,
    issue_description CLOB,
    status            VARCHAR2(50)                DEFAULT 'RECEIVED',
    received_date     TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    return_date       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_warranty_claims PRIMARY KEY (id),
    CONSTRAINT fk_warranty_item FOREIGN KEY (product_item_id) REFERENCES product_items (id),
    CONSTRAINT fk_warranty_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_warranty_staff FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_warranty_status CHECK (status IN ('RECEIVED', 'FIXING', 'FIXED', 'RETURNED', 'UNFIXABLE'))
);



CREATE TABLE inventory_sessions
(
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    created_by NUMBER(19, 0)                                      NOT NULL,
    status     VARCHAR2(20)             DEFAULT 'IN_PROGRESS',
    start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_date   TIMESTAMP,
    CONSTRAINT pk_inventory_sessions PRIMARY KEY (id),
    CONSTRAINT fk_inventory_user FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_inventory_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE inventory_details
(
    id            NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    session_id    NUMBER(19, 0),
    imei          VARCHAR2(50),
    expected_loc  NUMBER(19, 0),
    actual_loc    NUMBER(19, 0),
    record_status VARCHAR2(20),
    note          VARCHAR2(255),
    CONSTRAINT pk_inventory_details PRIMARY KEY (id),
    CONSTRAINT fk_inv_det_session FOREIGN KEY (session_id) REFERENCES inventory_sessions (id),
    CONSTRAINT fk_inv_det_expected FOREIGN KEY (expected_loc) REFERENCES warehouse_locations (id),
    CONSTRAINT fk_inv_det_actual FOREIGN KEY (actual_loc) REFERENCES warehouse_locations (id),
    CONSTRAINT ck_record_status CHECK (record_status IN ('MATCH', 'MISMATCH', 'MISSING', 'EXTRA'))
);

CREATE TABLE password_reset_tokens
(
    id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id     NUMBER              NOT NULL,
    token       VARCHAR2(255)       NOT NULL UNIQUE,
    expiry_date TIMESTAMP           NOT NULL,
    used        NUMBER(1) DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prt_user FOREIGN KEY (user_id) REFERENCES users (id)
);
