CREATE TABLE roles
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR2(50)                                          NOT NULL,
    description VARCHAR2(255),
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE users
(
    id                NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR2(100)                                         NOT NULL,
    full_name         VARCHAR2(255),
    password          VARCHAR2(255)                                         NOT NULL,
    gender            NUMBER(1),
    age               NUMBER(3),
    phone_number      VARCHAR2(20),
    email             VARCHAR2(255),
    status            VARCHAR2(20)                DEFAULT 'NEW',
    is_password_reset NUMBER(1)                   DEFAULT 0                 NOT NULL,
    role_id           NUMBER(19, 0)                                         NOT NULL,
    is_deleted        NUMBER(1)                   DEFAULT 0                 NOT NULL,
    last_login        TIMESTAMP(6) WITH TIME ZONE,
    created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT ck_users_is_deleted CHECK ( is_deleted IN (0, 1))
);

CREATE TABLE refresh_tokens
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    user_id     NUMBER(19, 0)               NOT NULL,
    token       VARCHAR2(500)               NOT NULL,
    expiry_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT fk_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE audit_logs
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    user_id     VARCHAR2(100),
    action      VARCHAR2(100),
    entity_name VARCHAR2(100),
    entity_id   VARCHAR2(100),
    status      VARCHAR2(50),
    details     CLOB,
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE products
(
    id            NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    sku           VARCHAR2(50)                                          NOT NULL,
    name          VARCHAR2(255),
    price_import  NUMBER(19, 2)               DEFAULT 0,
    price_export  NUMBER(19, 2)               DEFAULT 0,
    current_stock NUMBER(10)                  DEFAULT 0                 NOT NULL,
    min_threshold NUMBER(10)                  DEFAULT 5,
    status        VARCHAR2(20)                DEFAULT 'ACTIVE',
    created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uk_products_sku UNIQUE (sku)
);

CREATE TABLE product_items
(
    id          NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    product_id  NUMBER(19, 0) NOT NULL,
    imei        VARCHAR2(50)  NOT NULL,
    status      VARCHAR2(20)                DEFAULT 'AVAILABLE',
    order_id    NUMBER(19, 0),
    import_date TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sold_date   TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT pk_product_items PRIMARY KEY (id),
    CONSTRAINT uk_product_items_imei UNIQUE (imei),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products (id)
);


CREATE TABLE stock_movements
(
    id           NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    product_id   NUMBER(19, 0)                                         NOT NULL,
    type         VARCHAR2(20)                                          NOT NULL,
    action_type  VARCHAR2(20)                                          NOT NULL,
    quantity     NUMBER(10)                                            NOT NULL,
    reference_id NUMBER(19, 0),
    created_by   NUMBER(19, 0)                                         NOT NULL,
    note         VARCHAR2(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_stock_movements PRIMARY KEY (id),
    CONSTRAINT fk_move_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_move_type CHECK (type IN ('IMPORT', 'EXPORT', 'ADJUST'))
)